export const LANGUAGES = {
    CHINESE:{
        home:'首页',
        myOrder:'我的订单',
        me:'我',
        login:'登录',
        register:'注册',
        loginText:'登录/注册',
        myProfile:'我的档案',
        favoriteStore:'我的收藏',
        manageStore:'店铺管理',
        addBusiness:'添加店铺',
        contactUs:'联系我们',
        setting:'设置',
        logout:'登出',
        language:'语言',
        simplifiedChinese:'简体中文',
        english:'英语',
        telephoneNumber:'联系电话',
        email:'邮箱',
        wechat:'微信',
        location:'位置',
        payment:'支付',
        profile:'个人资料',
        firstName:'名字',
        lastName:'姓氏',
        homeAddress:'家庭地址',
        workAddress:'工作地址',
        previousAddress:'曾用地址',
        locationSetting:'设置地址',
        addBusiness:'添加商店',
        newBusiness:'新商店',
        information:'基本信息',
        items:'商品条目',
        contact:'联系信息',
        businessName:'商店名称',
        description:'简介',
        ownerName:'所有者名称',
        tags:'标签',
        website:'网站',
        address:'地址',
        addCategory:'添加类别',
        confirm:'确认',
        cancel:'取消',
        username:'用户名',
        password:'密码',
        forgetPassword:'忘记密码',
        welcome:'欢迎'
    },
    ENGLISH:{
        home:'Home',
        myOrder:'My orders',
        me:'Me',
        login:'Login',
        register:'Register',
        loginText:'Login/Register',
        myProfile: 'My Profile',
        favoriteStore:'My Favorites',
        manageStore:'Manage Store',
        addBusiness:'Add Businesses',
        contactUs:'Contact us',
        setting:'Settings',
        logout:'Logout',
        language:'Language',
        simplifiedChinese:'Simplified Chinese',
        english:'English',
        telephoneNumber:'Tel',
        email:'Email',
        wechat:'Wechat',
        location:'Location',
        payment:'Payment',
        profile:'Profile',
        firstName:'First name',
        lastName:'Last name',
        homeAddress:'Home address',
        workAddress:'Work address',
        previousAddress:'Previous addresses',
        locationSetting:'Location Setting',
        addBusiness:'Add Businesses',
        newBusiness:'New Business',
        information:'Information',
        items:'Items',
        contact:'Contact',
        businessName:'Business name',
        description:'Description',
        ownerName:'Owner name',
        tags:'Tags',
        website:'Website',
        address:'Address',
        addCategory:'Add category',
        confirm:'Confirm',
        cancel:'Cancel',
        username:'Username',
        password:'Password',
        forgetPassword:'Forget password',
        welcome:'Welcome'
    }
}