export const LANGUAGES = {
    CHINESE:{
        home:'首页',
        myOrder:'我的订单',
        me:'我',
        myProfile:'我的档案',
        favoriteStore:'我的收藏',
        manageStore:'店铺管理',
        addBusiness:'添加店铺',
        contactUs:'联系我们',
        setting:'设置',
        logout:'登出',
        language:'语言',
        simplifiedChinese:'简体中文',
        english:'英语',
    },
    ENGLISH:{
        home:'Home',
        myOrder:'My orders',
        me:'Me',
        myProfile: 'My Profile',
        favoriteStore:'Favorite Stores',
        manageStore:'Manage Store',
        addBusiness:'Add Businesses',
        contactUs:'Contact us',
        setting:'Setting',
        logout:'Logout',
        language:'Language',
        simplifiedChinese:'Simplified Chinese',
        english:'English',
    }
}