export const LANGUAGES = {
    CHINESE:{
        home:'首页',
        myOrder:'我的订单',
        me:'我',
        login:'登录',
        register:'注册',
        loginText:'登录/注册',
        myProfile:'我的档案',
        favoriteStore:'我的收藏',
        manageStore:'店铺管理',
        addBusiness:'添加店铺',
        contactUs:'联系我们',
        setting:'设置',
        logout:'登出',
        language:'语言',
        simplifiedChinese:'简体中文',
        english:'英语',
        telephoneNumber:'联系电话',
        email:'邮箱',
        wechat:'微信',
        location:'位置',
        payment:'支付',
    },
    ENGLISH:{
        home:'Home',
        myOrder:'My orders',
        me:'Me',
        login:'Login',
        register:'Register',
        loginText:'Login/Register',
        myProfile: 'My Profile',
        favoriteStore:'My Favorites',
        manageStore:'Manage Store',
        addBusiness:'Add Businesses',
        contactUs:'Contact us',
        setting:'Settings',
        logout:'Logout',
        language:'Language',
        simplifiedChinese:'Simplified Chinese',
        english:'English',
        telephoneNumber:'Tel',
        email:'Email',
        wechat:'Wechat',
        location:'Location',
        payment:'Payment',
    }
}